site_name: mkdocs-advanced-seo
site_description: The comprehensive, deep, and robust SEO plugin for MkDocs.
site_url: https://raineblog.dpdns.org/mkdocs-advanced-seo/
site_author: RainPPR

repo_name: entry/mkdocs-advanced-seo
repo_url: https://github.com/entry/mkdocs-advanced-seo

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.view

plugins:
  - social # MkDocs Material Social Cards
  - advanced-seo:
      use_canonical_url: true
      use_open_graph: true
      use_twitter_cards: true
      add_schema_org_json_ld: true
      # We rely on auto-detection for og_image from social cards, 
      # but provide a fallback if needed.
      # og_image: assets/fallback.png 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
